# Generated by Django 4.2.4 on 2023-08-23 15:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='место')),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 8, 23, 18, 26, 13, 821006), verbose_name='время')),
                ('action', models.CharField(max_length=150, verbose_name='действие')),
                ('is_pleasant_habit', models.BooleanField(blank=True, default=False, null=True, verbose_name='приятная привычка')),
                ('is_related_habit', models.BooleanField(blank=True, default=False, null=True, verbose_name='связанная привычка')),
                ('periodicity', models.PositiveSmallIntegerField(choices=[(1, 'ежедневная'), (2, 'еженедельная'), (3, 'eжемесячная')], default=1, verbose_name='периодичность')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='вознаграждение')),
                ('lead_time', models.TimeField(verbose_name='время выполнения')),
                ('is_published', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
