# Generated by Django 4.2.4 on 2023-08-26 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_remove_habit_is_related_habit_habit_pleasant_habit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 18, 49, 29, 578066), verbose_name='время'),
        ),
    ]
