# Generated by Django 4.2.4 on 2023-08-26 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_alter_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 18, 54, 2, 34869), verbose_name='время'),
        ),
    ]
